import PostLink from "@/components/posts/PostLink";
import { Post } from "@/types/Post";
import { PostPreview } from "@/types/PostPreview";

const ALLPOSTS: any[] = [
  {
    title: "[3] (post 1) (important!!)",
    section: "announcement",
    userRole: 2,
    userID: "1jnsu_ID",
    userFirstName: "1jinsu",
    userLastName: "1kwak",
    content: "post 1 content",
    isImportant: true,
    createdTime: 1693012446659,
    editedTime: null,
    postID: "1",
  },
  {
    title: "[5] (post 2) (long title) longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    section: "announcement",
    userRole: 1,
    userID: "2jnsu_ID",
    userFirstName: "2jinsu",
    userLastName: "2kwak",
    content: "post 2 content",
    isImportant: false,
    createdTime: 1691012446659,
    editedTime: null,
    postID: "2",
  },
  {
    title:
      "[4] (post 3) (important!!) (long title) (Root Admin) longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    section: "news",
    userRole: 3,
    userID: "3jnsu_ID",
    userFirstName: "3jinsu",
    userLastName: "3kwak",
    content: "post 3 content",
    isImportant: true,
    createdTime: 1692012446659,
    editedTime: null,
    postID: "3",
  },
  {
    title: "[6] (post 4) (long fname)",
    section: "news",
    userRole: 1,
    userID: "4jnsu_ID",
    userFirstName: "4jinsu_longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1690012446659,
    editedTime: null,
    postID: "4",
  },
  {
    title: "[2] (post 5) (long lname) title",
    section: "announcement",
    userRole: 1,
    userID: "5jnsu_ID",
    userFirstName: "5jinsu",
    userLastName: "5kwak_longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    content: "post 5 content",
    isImportant: false,
    createdTime: 1694012446659,
    editedTime: null,
    postID: "5",
  },
  {
    title: "[1] (post 6) (new) ",
    section: "news",
    userRole: 1,
    userID: "6jnsu_ID",
    userFirstName: "6jinsu",
    userLastName: "6kwak",
    content: "post 6 content",
    isImportant: false,
    createdTime: 1695012446659,
    editedTime: null,
    postID: "6",
  },
  {
    title: "[7](short)",
    section: "announcement",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1680012446659,
    editedTime: null,
    postID: "7",
  },
  {
    title: "[8] (post 4) (long fname)",
    section: "announcement",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4jinsu111111111",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1670012446659,
    editedTime: null,
    postID: "8",
  },
  {
    title: "[9] (post 4) (long fname)",
    section: "news",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1660012446659,
    editedTime: null,
    postID: "9",
  },
  {
    title: "[10] (post 4) (long fname)",
    section: "news",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1650012446659,
    editedTime: null,
    postID: "10",
  },
  {
    title: "[11] (post 4) (long fname)",
    section: "news",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1640012446659,
    editedTime: null,
    postID: "11",
  },
  {
    title: "IG Educational Forum Online Lecture – Session 3",
    section: "news",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1630012446659,
    editedTime: null,
    postID: "12",
  },
  {
    title: "[13] (post 4) (Root Admin)",
    section: "news",
    userRole: 3,
    userID: "9jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1620012446659,
    editedTime: null,
    postID: "13",
  },
  {
    title: "[14] (post 4) (long fname)",
    section: "news",
    userRole: 2,
    userID: "8jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1610012446659,
    editedTime: null,
    postID: "14",
  },
  {
    title: "[15] (post 4) (long fname)",
    section: "news",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1600012446659,
    editedTime: null,
    postID: "15",
  },
  {
    title: "[16] (post 4) (long fname)",
    section: "news",
    userRole: 1,
    userID: "7jnsu",
    userFirstName: "4jinsu",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: false,
    createdTime: 1590012446659,
    editedTime: null,
    postID: "16",
  },
];

const transformToPost = (data: any): Post => {
  return {
    title: data.title || "",
    section: data.section || "",
    userRole: data.userRole || 0,
    userID: data.userID || "",
    userFirstName: data.userFirstName || "",
    userLastName: data.userLastName || "",
    content: data.content || "",
    isImportant: data.isImportant || false,
    createdTime: data.createdTime || 0,
    editedTime: data.editedTime || null,
    postID: data.postID || 0,
  };
};

const transformToPostPreview = (data: any): PostPreview => {
  return {
    title: data.title || "",
    section: data.section || "",
    userRole: data.userRole || 0,
    userID: data.userID || "",
    userFirstName: data.userFirstName || "",
    userLastName: data.userLastName || "",
    isImportant: data.isImportant || false,
    createdTime: data.createdTime || 0,
    editedTime: data.editedTime || null,
    postID: data.postID || 0,
  };
};

export const transformedPostPreviews: PostPreview[] = ALLPOSTS.map(transformToPostPreview);
export const transformedPosts: PostPreview[] = ALLPOSTS.map(transformToPost);
