const ALLPOSTS = [
  {
    title: "[3] (post 1) (important!!)",
    section: "announcement",
    role: "Admin",
    userFirstName: "1jinsu",
    userLastName: "1kwak",
    content: "post 1 content",
    isImportant: true,
    createdTime: 1693012446659,
    editedTime: null,
    id: 1,
  },
  {
    title: "[5] (post 2) (long title) longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    section: "announcement",
    role: "Educator",
    userFirstName: "2jinsu",
    userLastName: "2kwak",
    content: "post 2 content",
    isImportant: true,
    createdTime: 1691012446659,
    editedTime: null,
    id: 2,
  },
  {
    title:
      "[4] (post 3) (important!!) (long title) (Root Admin) longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    section: "news",
    role: "RootAdmin",
    userFirstName: "3jinsu",
    userLastName: "3kwak",
    content: "post 3 content",
    isImportant: true,
    createdTime: 1692012446659,
    editedTime: null,
    id: 3,
  },
  {
    title: "[6] (post 4) (long fname)",
    section: "news",
    role: "Educator",
    userFirstName: "4jinsu_longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    userLastName: "4kwak",
    content: "post 4 content",
    isImportant: true,
    createdTime: 1690012446659,
    editedTime: null,
    id: 4,
  },
  {
    title: "[2] (post 5) (long lname) title",
    section: "announcement",
    role: "Educator",
    userFirstName: "5jinsu",
    userLastName: "5kwak_longggggggggggggggggggggggggggggggggggggggggggggggggggggggg",
    content: "post 5 content",
    isImportant: true,
    createdTime: 1694012446659,
    editedTime: null,
    id: 5,
  },
  {
    title: "[1] (post 6) (new) ",
    section: "news",
    role: "Educator",
    userFirstName: "6jinsu",
    userLastName: "6kwak",
    content: "post 6 content",
    isImportant: true,
    createdTime: 1695012446659,
    editedTime: null,
    id: 6,
  },
];

export default ALLPOSTS;
