import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/navigation/Header";
import { CssBaseline } from "@mui/material";
import ToastProvider from "@/components/ToastProvider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" style={{ height: "100%" }}>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <CssBaseline />
        <Header />
        <ToastProvider />
        <div className="flex-grow">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
